<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checklist_billpayment</name>
   <tag></tag>
   <elementGuidId>10f75c91-f74b-49e2-8d6f-58add90abca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/table/tbody/tr[1]/td[2]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4690d759-8f1b-4842-a029-63998e1d9c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topbar-select-terminal&quot;)/div[@class=&quot;sc-ciZhAO gYuUxt show&quot;]/input[1]</value>
      <webElementGuid>15213607-1973-4e7b-bb23-a64a2b4751dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>ff856164-859e-44d5-bddc-0872b356a69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topbar-select-terminal']/div[2]/input</value>
      <webElementGuid>a520671d-d2b3-45a4-99f1-b9464d834e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de06e553-a63d-4a93-9578-23017630bfa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
