<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Bypass_fa fa-check-circle</name>
   <tag></tag>
   <elementGuidId>fe393bfa-8bdd-40be-af93-243e8e2bfe07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-detail-container-content']/div/div/div[3]/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3252b51c-f7ae-422f-83f7-df4236f703fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check-circle</value>
      <webElementGuid>cfc1616a-08f2-4ed4-9e7c-f67eb7c9f497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-detail-container-content&quot;)/div[@class=&quot;MuiExpansionPanelDetails-root&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;input-group mb-3&quot;]/div[@class=&quot;input-group-append&quot;]/button[@class=&quot;btn btn-success&quot;]/i[@class=&quot;fa fa-check-circle&quot;]</value>
      <webElementGuid>2738f046-98fd-4719-a2ee-05682a01270a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[3]/div/div/button/i</value>
      <webElementGuid>324a0e05-b17d-4689-89a6-3c2d57d6cc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>6a1b92e1-57b0-4e3e-bfc4-6a1c148623a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
