<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customerName</name>
   <tag></tag>
   <elementGuidId>27624c38-2816-4695-81a5-92d4d257ad22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89bd1827-8ded-4a3f-94c1-fd5506e1930b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03420c61-cd2f-4cb8-b461-78ccb7031645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7ff12cd-365f-4c88-8a6b-6ad1e08437b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerName</value>
      <webElementGuid>e1a1d1a3-e070-4b3d-b1d6-ed99adaa2595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid</value>
      <webElementGuid>011c8827-3f7e-4c44-9dea-8c2ef9802de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>meraT</value>
      <webElementGuid>825a3468-6e63-4d40-b935-29510eb89641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-booking-information-content&quot;)/div[@class=&quot;MuiExpansionPanelDetails-root&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;input-icon&quot;]/input[@class=&quot;form-control is-invalid&quot;]</value>
      <webElementGuid>87fee609-82c6-4dd9-ac0f-6a239de17ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerName']</value>
      <webElementGuid>249b5925-e150-4e6f-923a-a90b797e5d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-booking-information-content']/div/div/div[5]/div/input</value>
      <webElementGuid>f1325746-572b-4620-9bda-6bfd9a58d0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[5]/div/input</value>
      <webElementGuid>4dff0181-cd63-47dc-b64a-daf7be13a45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerName']</value>
      <webElementGuid>26149f90-e4f1-4bfd-a3d4-e42b06fcf870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
