<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_VIA</name>
   <tag></tag>
   <elementGuidId>5a6621b4-22a5-407b-9d9d-e9fb8f6f2aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div/div[1]/div[2]/div/div[2]/div[2]/div/div/div/div/div[1]/div[1]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiExpansionPanelDetails-root > div.row > div.col-md-6 > label.form-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>764407db-d0c0-4d27-b956-a457bb55ceb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>5a4a11f1-4259-4548-86bf-6e79fcd13579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIA *</value>
      <webElementGuid>cf32609f-341f-42e0-a617-d2341f04daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-booking-information-content&quot;)/div[@class=&quot;MuiExpansionPanelDetails-root&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>6d6cde95-af82-4596-b846-a0cf8df3f662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-booking-information-content']/div/div/div/label</value>
      <webElementGuid>732719a8-7eb1-45df-ab34-963562ea6db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Information'])[1]/following::label[1]</value>
      <webElementGuid>94e645e9-7a72-48cd-863f-2516735de363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Limit Left'])[1]/following::label[1]</value>
      <webElementGuid>27be9e38-9a8e-402e-9e8a-c73089c03b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIA']/parent::*</value>
      <webElementGuid>49265c58-5f4b-4b1a-a1e3-56b888d62b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/label</value>
      <webElementGuid>38f2845e-fc45-466c-b6ad-11c7198a8005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'VIA *' or . = 'VIA *')]</value>
      <webElementGuid>6e03aed1-086e-4e19-a372-f230de0a14cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
