<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OOGNoYes</name>
   <tag></tag>
   <elementGuidId>800fe976-582a-4a35-b4c7-4efd1aa02be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='flagOog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flagOog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9842834e-3b72-47ac-aaa4-d4443e180b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined undefined</value>
      <webElementGuid>9436f7b2-6731-4319-a97b-7aa752e61dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>4916ee3d-5f2f-46ac-8b68-adb0fb1863b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>a6ed8d00-2d3e-419c-8c4f-2b0b5a3c5bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoYes</value>
      <webElementGuid>7e560d82-3bd7-4ea0-b29a-764e437f3881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flagOog&quot;)</value>
      <webElementGuid>c827938b-af21-4a6c-a0b0-b8f612e8fd1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flagOog']</value>
      <webElementGuid>8b86c61c-c14d-474e-a3ad-5612fba2a041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[26]/select</value>
      <webElementGuid>c3f1cf39-02d0-492c-8359-4afcf62633de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::select[1]</value>
      <webElementGuid>ce8260be-c8b4-4a43-8973-9df9fc72d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Front'])[1]/preceding::select[1]</value>
      <webElementGuid>c227b6e7-b171-4113-b889-01e4f386f798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Back'])[1]/preceding::select[1]</value>
      <webElementGuid>be25a5c8-6a4a-4f82-b450-c725cfe8c833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/select</value>
      <webElementGuid>7b3105e2-55fb-4952-89bc-987eae9c75ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'flagOog' and @id = 'flagOog' and (text() = 'NoYes' or . = 'NoYes')]</value>
      <webElementGuid>33b36b06-3e22-4fdd-9bf3-bf8840d48d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
