<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_HZNoYes</name>
   <tag></tag>
   <elementGuidId>a1c8ffe2-1625-474e-be04-434e7b05d91d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;hz&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flagOog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79847931-7099-4382-9c0d-e0ba417d12e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined undefined</value>
      <webElementGuid>960611d0-c7bd-4963-9a3d-38f06b2332ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>b613f971-a5b1-42a5-b917-c86f2d376938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>297e2278-c723-4926-8b0e-caa0a9337df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoYes</value>
      <webElementGuid>c4492ffd-b3ee-451f-841c-09ecb3f7f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flagOog&quot;)</value>
      <webElementGuid>3cd7bee7-162d-46cc-85c9-2ba636c4a78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flagOog']</value>
      <webElementGuid>a47f94c1-6b3f-4566-a504-5db45413d799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[26]/select</value>
      <webElementGuid>bd1b5c57-c310-4f4e-b557-fcc4b6ec5e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::select[1]</value>
      <webElementGuid>e4682761-0d28-4b9d-9c11-27d21693390c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Front'])[1]/preceding::select[1]</value>
      <webElementGuid>8f76f37a-3599-4288-847f-7d31d433cfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Back'])[1]/preceding::select[1]</value>
      <webElementGuid>929eacb3-45c5-40fa-8ca0-56e4b054c3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/select</value>
      <webElementGuid>f4efda18-d044-4422-9706-679fc6b66037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'flagOog' and @id = 'flagOog' and (text() = 'NoYes' or . = 'NoYes')]</value>
      <webElementGuid>9d741060-ba41-4c41-aefd-c91874fdf531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
