<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vessel</name>
   <tag></tag>
   <elementGuidId>9a1b2007-cd99-4d0f-beba-43e7ee1211da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div/div[1]/div[2]/div/div[1]/div[2]/div/div/div/div/div/div/div[1]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#containerSize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>933a7514-5323-4118-a3cf-5701e5dd077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>8d5160c0-a312-498b-8b05-9e125ea85304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>b1872b67-0f34-435a-b3d6-a09390960454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>c994e755-bbb9-4a79-afbf-d26b7f9ec9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2040452142</value>
      <webElementGuid>0c6cd670-ac9b-4586-96b7-fd818bcd77d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerSize&quot;)</value>
      <webElementGuid>beb0c009-8a3a-4097-bd7b-7f0db20637d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='containerSize']</value>
      <webElementGuid>fd0f9381-fdcd-4bd6-a567-1ad72e13ff53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[4]/select</value>
      <webElementGuid>ea31b3ba-ba69-4da6-9b55-8c39b20f40e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>df0e0d34-619a-424e-b743-15e04ec76b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>bfbac7dc-0c5b-4f8f-a20e-06e1066d2077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div[4]/select</value>
      <webElementGuid>167955f6-77fb-4fef-aeef-09708b3ab4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'containerSize' and @id = 'containerSize' and (text() = '2040452142' or . = '2040452142')]</value>
      <webElementGuid>07eaa542-7c16-4b00-ad26-507a1d700f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
