<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON - Copy</name>
   <tag></tag>
   <elementGuidId>65944cc5-cfaa-48c1-8446-a782a180f2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fpod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a6a80df-1642-4f16-9fbc-c9fa4b76f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>b1eb8a7a-2fa5-470c-a148-772637acf940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fpod</value>
      <webElementGuid>fca8cd34-324a-40a3-bd71-b84fee014200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fpod</value>
      <webElementGuid>5b2bb359-2bc6-44f7-8168-dddb2df8b944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON</value>
      <webElementGuid>adca9bf3-74d0-4e09-8b49-736d82af6a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fpod&quot;)</value>
      <webElementGuid>b6524ce4-2b75-4156-a1c2-c74a258c8170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fpod']</value>
      <webElementGuid>5477f887-ec08-41bd-9263-f1bd49e040fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-booking-information-content']/div/div/div[3]/select</value>
      <webElementGuid>7fb5fdae-c22d-4eef-8ebd-193ed08a990d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>0d684fdd-a6b1-4cce-af87-96725f5168fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>c9f0b68b-8c1b-48d6-baa0-1a77349931cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>4ef5d6bf-fa46-4bfa-abc4-a79e79c85902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fpod' and @id = 'fpod' and (text() = 'SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON' or . = 'SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON')]</value>
      <webElementGuid>dfe0c8ef-dda6-4c4c-a607-d579bf20f839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
