<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Height</name>
   <tag></tag>
   <elementGuidId>ef694d3b-2018-4fb4-9be5-ab7f98a3d360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;containerHeight&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#containerSize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eff8a05b-2dd5-4c9e-81ef-efd211a0cd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>c9c1c660-973b-4d7b-8dd2-d22028988013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>fa17c9a4-6374-4749-b084-22ed3feefea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>610df6ae-f54b-4928-9782-7a1666f8ab65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2040452142</value>
      <webElementGuid>1832d3cb-5f2a-4a07-84df-68bd330b0c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerSize&quot;)</value>
      <webElementGuid>c90ed0a9-83d0-4563-9880-fe530a914841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='containerSize']</value>
      <webElementGuid>5f22ef64-4725-41bd-95fd-7851295f7773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[4]/select</value>
      <webElementGuid>e8494790-8862-41bf-9f43-feae396dc54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>3564e71b-3bb0-4ec3-be67-1a054040174a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>cd0ecf80-10ff-497e-a7a1-a3d4028540e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div[4]/select</value>
      <webElementGuid>a14f1f13-c7f7-417d-b8df-3f7cc86de1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'containerSize' and @id = 'containerSize' and (text() = '2040452142' or . = '2040452142')]</value>
      <webElementGuid>0b805b1e-35e8-4b40-a661-cda6699753fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
