<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ODNoYes</name>
   <tag></tag>
   <elementGuidId>ba24f832-8e2d-4f55-9e4f-44de4a16eb78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='flagOog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flagOog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de551329-531d-4ca5-8213-f940f256bc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined undefined</value>
      <webElementGuid>6119f2a0-ba43-47cf-9203-ff8c4184a93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>ae883bca-ec29-4e00-a501-9d7d56ba1a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>e5587d05-bc3f-4bdd-a2f2-8fe4c41b0a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoYes</value>
      <webElementGuid>1441fb4f-0363-45c5-bfb6-3901d41e06ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flagOog&quot;)</value>
      <webElementGuid>f97374e0-1fc4-4caa-9865-1c7803bfb878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flagOog']</value>
      <webElementGuid>290b0d09-9442-48e1-9b41-c5c0f8b03ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[26]/select</value>
      <webElementGuid>b2ab0fd0-6f8a-44cb-8c30-ce1bb4a9e293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::select[1]</value>
      <webElementGuid>af2c692c-2c97-47ff-943e-e19c8fbfd32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Front'])[1]/preceding::select[1]</value>
      <webElementGuid>d7f4a8fd-1fc7-4050-a93c-1d51c26ed82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Back'])[1]/preceding::select[1]</value>
      <webElementGuid>d5968ea0-8ae1-4b45-b986-40fa57d2a783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/select</value>
      <webElementGuid>adca3fda-d71f-4a03-8341-2b537efdd8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'flagOog' and @id = 'flagOog' and (text() = 'NoYes' or . = 'NoYes')]</value>
      <webElementGuid>2aa64d73-8dcb-4568-a8b3-744e73978fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
