<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SlingNoYes</name>
   <tag></tag>
   <elementGuidId>5f1156a9-855b-4354-bc07-444cf0e09bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sling&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flagOog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>056b0a77-50f5-47a9-9ca0-0d1f376e7c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined undefined</value>
      <webElementGuid>b96f3ce8-442b-411d-adda-59f57301c8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>2d5f5f38-2791-455f-a32a-95a2dcc890ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flagOog</value>
      <webElementGuid>f496f4d7-5d61-4cb1-9fca-f12dd4669996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoYes</value>
      <webElementGuid>98268746-b3ec-49e7-8e6d-32a380149a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flagOog&quot;)</value>
      <webElementGuid>6d8e6e11-a215-4f2c-8c5c-0e183c37b0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flagOog']</value>
      <webElementGuid>95db713e-194e-4217-9dc1-d9faee20721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[26]/select</value>
      <webElementGuid>9a080382-13ab-49c4-a615-33c4c469782a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::select[1]</value>
      <webElementGuid>398d204b-0dd6-4332-863f-eeb2ff47f3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Front'])[1]/preceding::select[1]</value>
      <webElementGuid>e6534e83-0c1e-4039-85d6-7ceb13f1dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Over Back'])[1]/preceding::select[1]</value>
      <webElementGuid>23f9e164-e0b7-43b0-9e5f-1f6f36993d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/select</value>
      <webElementGuid>09cd4a61-16a4-4d7f-879a-b61765d515b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'flagOog' and @id = 'flagOog' and (text() = 'NoYes' or . = 'NoYes')]</value>
      <webElementGuid>4f9f5b6f-21ad-46ef-a2b1-659d0a8addef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
