<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON</name>
   <tag></tag>
   <elementGuidId>30315e21-3cfd-4d44-872d-28ccd6808762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fpod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fpod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>82f51437-a5b6-49bf-9100-948faf3b385c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>3827f254-f30c-4554-9943-94976ac66bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fpod</value>
      <webElementGuid>72ed6551-66d9-4e3f-b42e-e61056ab0c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fpod</value>
      <webElementGuid>4a38f47f-c110-4ece-aec3-b5ea52057606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON</value>
      <webElementGuid>04624468-539d-4f1e-afd6-fe435ee1171c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fpod&quot;)</value>
      <webElementGuid>639829b4-01d2-4b90-a9f5-ea7bb686428e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fpod']</value>
      <webElementGuid>4dd20176-fc1f-4fe5-8e9f-9ebcaade9be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-booking-information-content']/div/div/div[3]/select</value>
      <webElementGuid>b525a81f-c486-43f9-a7af-42e52499f925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>4d8484a7-3a5f-4034-be61-6f58aa35c1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>d2cf9206-c2af-4587-8507-eb08137ef6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>5d9d83f7-f7bc-4ce6-96aa-f4826b234546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fpod' and @id = 'fpod' and (text() = 'SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON' or . = 'SGSIN - SINGAPOREIDBLW - BELAWAN, INDONESIAJPTYO - TOKYO, JAPANIDMAK - IDMAKIDJKT - JAKARTA, INDONESIAIDSUB - SURABAYA, INDONESIAIDAMQ - AMBON')]</value>
      <webElementGuid>541d0af5-ad33-4a7b-8b02-43352dadf3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
