<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__carrierCode</name>
   <tag></tag>
   <elementGuidId>3b27334e-fca2-423e-a031-9d3400058f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='carrierCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#carrierCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4768c054-f139-44cc-8c4a-afa8283cf48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>a594b00a-18ec-45dc-883e-96f19238119d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrierCode</value>
      <webElementGuid>5e85a8f3-433b-448d-9d59-e89be5680cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carrierCode</value>
      <webElementGuid>8d539336-9ab2-44e3-a27a-8563f554237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carrierCode&quot;)</value>
      <webElementGuid>40f38bed-b486-46c2-ad3c-06eccdcca11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='carrierCode']</value>
      <webElementGuid>daa5c965-8503-4f64-be95-8e66ee6e3549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[21]/select</value>
      <webElementGuid>4a6e6ef2-38e4-45b4-9885-93c864e283fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/select</value>
      <webElementGuid>ab02c26e-6732-4d22-82f9-a92730cee169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'carrierCode' and @id = 'carrierCode']</value>
      <webElementGuid>2ccb75e9-77d8-4611-b8ee-a591d3e5c59a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
