<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ISO Code</name>
   <tag></tag>
   <elementGuidId>c2240128-e109-4097-8863-95ac9fcfe4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div/div[1]/div[2]/div/div[3]/div[2]/div/div/div/div/div[1]/div[22]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#containerSize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab3d3e84-ccc1-4521-9295-dd8fc6e4fe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control undefined </value>
      <webElementGuid>7dc0a790-4e10-4d05-931c-241477237f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>f34d7061-6739-46cd-b4f0-b7bba9797148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>containerSize</value>
      <webElementGuid>efdcebeb-0c81-4d05-9bd5-0a622ad30b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2040452142</value>
      <webElementGuid>d8bba280-96b2-4cd0-8393-c1e07fdaab8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerSize&quot;)</value>
      <webElementGuid>a1feb3ce-cd99-46ad-bc3b-772c4e90138f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='containerSize']</value>
      <webElementGuid>1d089a3d-877d-4e26-b087-64987aa4d728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-detail-container-content']/div/div/div[4]/select</value>
      <webElementGuid>eb96b6a5-c89e-468b-b80c-94559efc6026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>c8733407-e725-4dc9-9955-9cf2e6e831a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>818c0dbd-44d5-440d-8918-eb7a81bbdd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div[4]/select</value>
      <webElementGuid>65613845-7ca5-4327-abb9-db054f98ee8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'containerSize' and @id = 'containerSize' and (text() = '2040452142' or . = '2040452142')]</value>
      <webElementGuid>349a1779-154b-4323-8c9b-3f3bbebcb899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
